### PR TITLE
Bump build

### LINKED ISSUE #20: Cannot find package on M1
As reported in https://github.com/spacetelescope/synphot_refactor/issues/358

@mwcraig , how do we build this package on M1? `synphot` is Astropy Affiliated. Are you able to help? Thanks!

### PR DESCRIPTION
**Pull request by pllim**
Bump build to see if we pick up new archs like M1.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #20 

xref https://github.com/spacetelescope/synphot_refactor/issues/358

### CODE REVIEW

**Comment by pllim** [comment]
@conda-forge-admin, please rerender

**Comment by pllim** [comment]
@conda-forge-admin, please rerender

**Comment by pllim** [comment]
I don't understand the error

```
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/api.py", line 253, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 3799, in build_tree
    packages_from_this = build(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/build.py", line 2668, in build
    utils.check_call_env(
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 450, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda_build/utils.py", line 426, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/synphot_1691159953056/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

**Comment by pllim** [comment]
@mwcraig , how do I fix the failure? 🙏

**Comment by pllim** [comment]
@conda-forge/help-osx-arm64 help 🙏

**Comment by erykoff** [comment]
In your `build` section of meta.yaml, you need:

```
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
```

Also, the `numpy` line in the `run` section should be `{{ pin_compatible('numpy') }}`.  See eg https://github.com/conda-forge/hpgeom-feedstock/blob/main/recipe/meta.yaml

**Comment by erykoff** [comment]
They're not magic, they're just advanced technology!  https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by pllim** [comment]
Thanks for your help, @erykoff !

**Pull request merged**
